//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CsharpSubset.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICsharpSubsetListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class CsharpSubsetBaseListener : ICsharpSubsetListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] CsharpSubsetParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] CsharpSubsetParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.usingStmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsingStmnt([NotNull] CsharpSubsetParser.UsingStmntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.usingStmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsingStmnt([NotNull] CsharpSubsetParser.UsingStmntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.classInitialization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassInitialization([NotNull] CsharpSubsetParser.ClassInitializationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.classInitialization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassInitialization([NotNull] CsharpSubsetParser.ClassInitializationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.classDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDefinition([NotNull] CsharpSubsetParser.ClassDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.classDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDefinition([NotNull] CsharpSubsetParser.ClassDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.propertyDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyDefinition([NotNull] CsharpSubsetParser.PropertyDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.propertyDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyDefinition([NotNull] CsharpSubsetParser.PropertyDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.methodDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDefinition([NotNull] CsharpSubsetParser.MethodDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.methodDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDefinition([NotNull] CsharpSubsetParser.MethodDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.stmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmnt([NotNull] CsharpSubsetParser.StmntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.stmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmnt([NotNull] CsharpSubsetParser.StmntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.varDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclaration([NotNull] CsharpSubsetParser.VarDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.varDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclaration([NotNull] CsharpSubsetParser.VarDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.assignStmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignStmnt([NotNull] CsharpSubsetParser.AssignStmntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.assignStmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignStmnt([NotNull] CsharpSubsetParser.AssignStmntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.returnStmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmnt([NotNull] CsharpSubsetParser.ReturnStmntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.returnStmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmnt([NotNull] CsharpSubsetParser.ReturnStmntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CsharpSubsetParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CsharpSubsetParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.mathExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathExpression([NotNull] CsharpSubsetParser.MathExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.mathExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathExpression([NotNull] CsharpSubsetParser.MathExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.methodCallStmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCallStmnt([NotNull] CsharpSubsetParser.MethodCallStmntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.methodCallStmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCallStmnt([NotNull] CsharpSubsetParser.MethodCallStmntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] CsharpSubsetParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] CsharpSubsetParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgList([NotNull] CsharpSubsetParser.ArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgList([NotNull] CsharpSubsetParser.ArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.lambdaExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaExpression([NotNull] CsharpSubsetParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.lambdaExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaExpression([NotNull] CsharpSubsetParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.lambdaBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaBody([NotNull] CsharpSubsetParser.LambdaBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.lambdaBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaBody([NotNull] CsharpSubsetParser.LambdaBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.lambdaArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaArgs([NotNull] CsharpSubsetParser.LambdaArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.lambdaArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaArgs([NotNull] CsharpSubsetParser.LambdaArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] CsharpSubsetParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] CsharpSubsetParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] CsharpSubsetParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] CsharpSubsetParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReference([NotNull] CsharpSubsetParser.ReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReference([NotNull] CsharpSubsetParser.ReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.delegateType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDelegateType([NotNull] CsharpSubsetParser.DelegateTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.delegateType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDelegateType([NotNull] CsharpSubsetParser.DelegateTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.compileUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompileUnit([NotNull] CsharpSubsetParser.CompileUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.compileUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompileUnit([NotNull] CsharpSubsetParser.CompileUnitContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
