//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CsharpSubset.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CsharpSubsetParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ICsharpSubsetVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] CsharpSubsetParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.usingStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingStmnt([NotNull] CsharpSubsetParser.UsingStmntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.classInitialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassInitialization([NotNull] CsharpSubsetParser.ClassInitializationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.classDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDefinition([NotNull] CsharpSubsetParser.ClassDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.propertyDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyDefinition([NotNull] CsharpSubsetParser.PropertyDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.methodDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDefinition([NotNull] CsharpSubsetParser.MethodDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.stmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmnt([NotNull] CsharpSubsetParser.StmntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.varDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDeclaration([NotNull] CsharpSubsetParser.VarDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.assignStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStmnt([NotNull] CsharpSubsetParser.AssignStmntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.returnStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmnt([NotNull] CsharpSubsetParser.ReturnStmntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CsharpSubsetParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.mathExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMathExpression([NotNull] CsharpSubsetParser.MathExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.methodCallStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallStmnt([NotNull] CsharpSubsetParser.MethodCallStmntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.lambdaBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaBody([NotNull] CsharpSubsetParser.LambdaBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpression([NotNull] CsharpSubsetParser.LambdaExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] CsharpSubsetParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.typedArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedArgList([NotNull] CsharpSubsetParser.TypedArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] CsharpSubsetParser.ArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] CsharpSubsetParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] CsharpSubsetParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReference([NotNull] CsharpSubsetParser.ReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.delegateType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelegateType([NotNull] CsharpSubsetParser.DelegateTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CsharpSubsetParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompileUnit([NotNull] CsharpSubsetParser.CompileUnitContext context);
}
