//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CsharpSubset.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CsharpSubsetParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ICsharpSubsetListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CsharpSubsetParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CsharpSubsetParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.usingStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsingStmnt([NotNull] CsharpSubsetParser.UsingStmntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.usingStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsingStmnt([NotNull] CsharpSubsetParser.UsingStmntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.classInitialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassInitialization([NotNull] CsharpSubsetParser.ClassInitializationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.classInitialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassInitialization([NotNull] CsharpSubsetParser.ClassInitializationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.classDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDefinition([NotNull] CsharpSubsetParser.ClassDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.classDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDefinition([NotNull] CsharpSubsetParser.ClassDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.propertyDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyDefinition([NotNull] CsharpSubsetParser.PropertyDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.propertyDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyDefinition([NotNull] CsharpSubsetParser.PropertyDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.methodDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDefinition([NotNull] CsharpSubsetParser.MethodDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.methodDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDefinition([NotNull] CsharpSubsetParser.MethodDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.stmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmnt([NotNull] CsharpSubsetParser.StmntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.stmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmnt([NotNull] CsharpSubsetParser.StmntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.varDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclaration([NotNull] CsharpSubsetParser.VarDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.varDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclaration([NotNull] CsharpSubsetParser.VarDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.assignStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignStmnt([NotNull] CsharpSubsetParser.AssignStmntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.assignStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignStmnt([NotNull] CsharpSubsetParser.AssignStmntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.returnStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmnt([NotNull] CsharpSubsetParser.ReturnStmntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.returnStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmnt([NotNull] CsharpSubsetParser.ReturnStmntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CsharpSubsetParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CsharpSubsetParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.mathExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMathExpression([NotNull] CsharpSubsetParser.MathExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.mathExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMathExpression([NotNull] CsharpSubsetParser.MathExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.methodCallStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCallStmnt([NotNull] CsharpSubsetParser.MethodCallStmntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.methodCallStmnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCallStmnt([NotNull] CsharpSubsetParser.MethodCallStmntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] CsharpSubsetParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] CsharpSubsetParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] CsharpSubsetParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] CsharpSubsetParser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaExpression([NotNull] CsharpSubsetParser.LambdaExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaExpression([NotNull] CsharpSubsetParser.LambdaExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.lambdaBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaBody([NotNull] CsharpSubsetParser.LambdaBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.lambdaBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaBody([NotNull] CsharpSubsetParser.LambdaBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.lambdaArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaArgs([NotNull] CsharpSubsetParser.LambdaArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.lambdaArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaArgs([NotNull] CsharpSubsetParser.LambdaArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] CsharpSubsetParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] CsharpSubsetParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] CsharpSubsetParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] CsharpSubsetParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReference([NotNull] CsharpSubsetParser.ReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReference([NotNull] CsharpSubsetParser.ReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.delegateType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelegateType([NotNull] CsharpSubsetParser.DelegateTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.delegateType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelegateType([NotNull] CsharpSubsetParser.DelegateTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CsharpSubsetParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompileUnit([NotNull] CsharpSubsetParser.CompileUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CsharpSubsetParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompileUnit([NotNull] CsharpSubsetParser.CompileUnitContext context);
}
